.circleci/config.yml, CHANGELOG.md, do, runner-init/Dockerfile, runner-init/fake-agent.Dockerfile, runner-init/init.sh
**Ticket/s**:
https://circleci.atlassian.net/browse/ONPREM-1263
---
**Change Type**:
*Why this change? Reference the ticket and acceptance criteria if any. Specify the type of change: bug fix, new feature, breaking change, documentation update, security, etc.*
---
*What was the solution? How did you fix the issue or implement the new feature?*
---
*Describe what was tested. Remember to include changes in functionality, edge cases, and enough detail that another developer can replicate your progress.*
---
*Have any updates been made to the documentation?*
=> Download task agent binaries directly via the Dockerfile

.circleci/config.yml
https://circleci.atlassian.net/browse/ONPREM-1274
---
I think we were doing this, but it got lost at some point. Anyhow, this is something we should _definitely_ be doing.
---
---
---
=> Scan for vulnerabilities [ONPREM-1274]

CHANGELOG.md, acceptance/acceptance_test.go, acceptance/init_test.go, cmd/orchestrator/main.go, cmd/orchestrator/testdata/help.txt, cmd/orchestrator/testdata/init.txt
Jira: https://circleci.atlassian.net/browse/ONPREM-1263
---
- Add an acceptance test framework and cases for the init command.
- Update the CLI configuration to account for limitations on positional arguments of the ex test runner.
---
---
This PR introduces the first acceptance tests for this project.
---
=> Add acceptance tests [ONPREM-1263]

.circleci/config.yml
=> Notify Slack on release

internal/testing/ci/smoke/smoke_test.go
This allows us to only need to trigger the relevant driver tests for each project
---
---
---
---
=> Make each driver optional on the smoke tester [ONPREM-1297]

CHANGELOG.md, acceptance/task_test.go, go.mod, task/config.go, task/config_test.go
=> Add checksum validation on task config

.goreleaser/binaries.yaml, .goreleaser/dockers.yaml, do
=> Upgrade GoReleaser to v2 (for real this time) [ONPREM-1249]

CHANGELOG.md, cmd/orchestrator/main.go, cmd/orchestrator/testdata/run-task.txt, task/config.go, task/orchestrator.go, task/orchestrator_test.go
=> Handle shutdown of a task with a termination grace period

CHANGELOG.md, task/orchestrator.go, task/orchestrator_test.go
=> Use the task context for stopping the process reaper

CHANGELOG.md, clients/runner/client.go, clients/runner/client_test.go, cmd/orchestrator/main.go, go.mod, internal/testing/fakerunnerapi/fakerunnerapi.go, task/orchestrator.go, task/orchestrator_test.go
We'll eventually need this to retry or infra-fail tasks
---
---
---
---
=> Implement an HTTP client for the runner API

.circleci/config.yml, .goreleaser/dockers.yaml, CHANGELOG.md, cosign.pub, do
Jira: https://circleci.atlassian.net/browse/ONPREM-441
---
---
---
Testing:
- https://app.circleci.com/pipelines/github/circleci/runner-init/186/workflows/14cdcb9b-17a6-4288-9cc9-39b809ef6fba/jobs/730?invite=true#step-108-3097_27
- https://app.circleci.com/pipelines/github/circleci/runner-init/186/workflows/14cdcb9b-17a6-4288-9cc9-39b809ef6fba/jobs/730/parallel-runs/0/steps/0-109
---
=> [ONPREM-441] Sign the init images and manifests

CHANGELOG.md, clients/runner/client.go, clients/runner/client_test.go, internal/testing/fakerunnerapi/fakerunnerapi.go, task/config.go, task/config_test.go, task/orchestrator.go, task/orchestrator_test.go
---
This is the last essential piece for the GOAT implementation outside of integrating it with the runner agent.
---
---
---
=> Wire up the runner API client

CHANGELOG.md, task/cmd/cmd.go, task/cmd/reaper.go, task/orchestrator.go, task/orchestrator_test.go
=> Refactor command execution and ensure cleanup of the process group [ONPREM-1263]

.goreleaser/dockers.yaml
Just a quick revert of the image tag name for the test images
=> Drop s from test image tag

renovate.json
=> Extend backplane Renovate config

CHANGELOG.md, cmd/orchestrator/main.go
=> Don't error if interrupted [ONPREM-1379]

CHANGELOG.md, task/cmd/cmd.go, task/cmd/prefixsuffixsaver.go, task/orchestrator.go, task/orchestrator_test.go
=> Supplement task agent errors with stderr and an action to check logs

renovate.json
https://github.com/circleci/runner-init/issues/42
---
---
---
---
=> Fix renovate.json [ONPREM-1567]

.circleci/config.yml, do
ONPREM-1560 
- Generating `dev` version images which builds on `not-main` branches
---
---
---
---
- [] Updated [changelog](https://github.com/circleci/runner-init/blob/main/CHANGELOG.md)
=> ONPREM-1560 | Generate dev images

.circleci/config.yml, .goreleaser/dockers.yaml, do
These should only be published on `main` for use in the `circleci-runner` acceptance tests
---
---
---
---
=> Don't push `test-agent` images on dev branches

.webhook-ci.yml
For got `then` in the bash branching for webhooks. This adds `then`
=> fix bash if statements for webhook

do
---
For dogfooding in K9s
---
---
---
=> Publish a server candidate version of runner-init

.webhook-ci.yml
Needed to quote the incoming webhook json payload or bash gets sad.
=> quote webhook payload for CI

internal/testing/ci/smoke/smoke_test.go, internal/testing/ci/smoke/tester.go
---
---
---
:question: **Testing**'
https://app.circleci.com/pipelines/github/circleci/runner-init/716/workflows/9ea68c07-de90-4ba0-890c-cb7478ea53e9/jobs/2150?invite=true#step-103-1310_135
---
=> Run K8s smoke tests in server K9s [ONPREM-1371]

do
We've now code-freezed for 4.7, so the new RC is 4.8.
This will resolve these failures in the nightly smoke tests: https://app.k9s.sphereci.com/pipelines/github/circleci/runner-smoke-tests/74/workflows/d15dc9f4-d0c8-4fc2-80a1-1766ff6e6e3c/jobs/535?invite=true#step-0-8829_126
---
---
---
---
=> Update server versions to publish images for [ONPREM-1472]

internal/testing/ci/smoke/tester.go
workflow-run seems to 404 on server
---
---
---
---
=> Use server-compatible URL for workflow in smoke tests

.webhook-ci.yml
Simpler, doesn't require a Circle token, and won't make our Pipelines look red
---
---
---
---
=> Use step halt instead of cancel workflow in webhook filter [ONPREM-1719]

.webhook-ci.yml
=> Fix call to trigger image rebuild

.webhook-ci.yml
Core issue was the org slug was missing from the path. Also we don't need to specify the main branch specifically; it'll be used by default. We already block triggers on dev branches.
---
---
---
---
=> Fix pipeline trigger call in webhook workflow

README.md
Just to ensure our testing strategies are compliant with the testing P&P
---
---
---
---
=> Add note on integration tests in README

.circleci/config.yml
=> Try go-cache

.circleci/config.yml, .webhook-ci.yml
---
Should resolve this: https://app.circleci.com/pipelines/github/circleci/runner-init/1840/workflows/f4fed306-981b-4008-b4e3-5408acbdd836/jobs/4058?invite=true#step-102-1_34
---
---
---
=> Fix typo in curl to trigger pipeline from webhook workflow

.circleci/config.yml
GOAT is now released
---
---
---
---
=> Stop using experimental version in smoke tests

LICENSE
=> Add LICENSE [ONPREM-1925]

go.mod, go.sum
Wiz has determined this is vulnerable
=> fix(deps): Upgrade go-jose to 3.0.4

do
We've now code-freezed for 4.8, so the new RC (k9s/server-staging) is 4.9.
=> ONPREM-1986 | update do script for server-4.9.0

internal/testing/ci/smoke/smoke_test.go
=> Temporarily run the container runner smoke tests in cloud

task/orchestrator_test.go
This test is a bit flaky on Windows because of the sleep, so let's add a poller with a reasonable timeout
---
---
---
---
=> Use poller in flaky orchestrator test

README.md
=> [ONPREM-1832] Document Windows preview in README

task/orchestrator.go, task/orchestrator_test.go
There have been some reports of this check failing with an ambiguous error. This improves it by using a buffered watcher.Events channel to prevent a potential race condition, enabling retries when this error occurs so tasks can be unclaimed, and providing a clearer error message.
- https://circleci.atlassian.net/browse/ONPREM-2489
- https://circleci.atlassian.net/browse/ONPREM-2431
---
---
---
---
=> [ONPREM-2431] Improve service container readiness check resiliency
